name: Compila con Maven

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate report
        run: mvn jacoco:prepare-agent install jacoco:report

      - name: Generate Jacoco report
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.6.1
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: .github/badges

      - name: Log coverage percentage
        run: |
          echo "Code coverage = ${{ steps.jacoco.outputs.coverage}}"
          echo "Branches coverage = ${{ steps.jacoco.outputs.branches}}"
      - name: Add badges
        run: git add .github/badges/.

      - name: Commit files
        run: |
          git config --global user.name 'github-actions'
          git commit -m "Added coverage badges" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Coveralls Coverage Report Submission
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: mvn -B coveralls:report